from manim import *
class start(Scene):
    def construct(self):
        t1=Tex("Sum of factors of $8$").shift(UP*2)
        t2=Tex("$1+2+4+8=15$").shift(UP*1)
        t3=Tex("Sum of factors of $7 +$ Sum of factors of $6 -$")
        t4=Tex("Sum of factors of $3 -$ Sum of factors of $1$").shift(DOWN*1)
        ei=Tex("$8+$",color=RED).shift(LEFT*1)
        tw=Tex("$12-$",color=RED).shift(RIGHT*1)
        fo=Tex("$4-$",color=RED).shift(DOWN*1+LEFT*1)
        on=Tex("$1$",color=RED).shift(DOWN*1+RIGHT*1)
        fin1=Tex("$=15$",color=GREEN).shift(DOWN*3)
        p1=Tex("Sum of factors of $9$").shift(UP*2)
        p2=Tex("$1+3+9=13$").shift(UP*1)
        p3=Tex("Sum of factors of $8 +$ Sum of factors of $7 -$")
        p4=Tex("Sum of factors of $4 -$ Sum of factors of $2$").shift(DOWN*1)
        fif=Tex("$15+$",color=RED).shift(LEFT*1)
        ei1=Tex("$8-$",color=RED).shift(RIGHT*1)
        sev=Tex("$7-$",color=RED).shift(DOWN*1+LEFT*1)
        th=Tex("$3$",color=RED).shift(DOWN*1+RIGHT*1)
        fin2=Tex("$=13$",color=GREEN).shift(DOWN*3)
        self.play(Write(t1))
        self.wait(4)
        self.play(Write(t2))
        self.wait(5)
        self.play(Write(t3))
        self.play(Write(t4))
        self.wait(4)
        self.play(FadeIn(ei),ei.animate.shift(DOWN*2+LEFT*0.5))
        self.play(FadeIn(tw),tw.animate.shift(DOWN*2+LEFT*1.5))
        self.play(FadeIn(fo),fo.animate.shift(DOWN*1+RIGHT*1.75))
        self.play(FadeIn(on),on.animate.shift(DOWN*1+RIGHT*0.5))
        self.play(Write(fin1))
        self.wait(5)
        self.play(FadeOut(ei,tw,fo,on,fin1))
        self.play(Transform(t1,p1))
        self.wait(2)
        self.play(Transform(t2,p2))
        self.play(Transform(t3,p3))
        self.play(Transform(t4,p4))
        self.play(FadeIn(fif),fif.animate.shift(DOWN*2+LEFT*0.5))
        self.play(FadeIn(ei1),ei1.animate.shift(DOWN*2+LEFT*1.5))
        self.play(FadeIn(sev),sev.animate.shift(DOWN*1+RIGHT*1.75))
        self.play(FadeIn(th),th.animate.shift(DOWN*1+RIGHT*0.5))
        self.play(Write(fin2))
        self.wait(20)
        
class intro(Scene):
    def construct(self):
        primes=Tex("$2\,\,3\,\,5\,\,7\,\,11\,\,13\,\,17\,\,19\,\,23\,\,29$").shift(UP*2)
        primes2=Tex("$31\,\,37\,\,41\,\,43\,\,47\,\,53\,\,59\,\,61\,\,67$").scale(0.5).shift(UP*1)
        primes3=Tex("$71\,\,73\,\,79\,\,83\,\,89\,\,97\,\,101\,\,103$").scale(0.25)
        primes4=Tex("$107\,\,109\,\,113\,\,127\,\,131\,\,137\,\,139\,\,149\,\,151\,\,157$").scale(0.125).shift(DOWN*1)
        primes5=Tex("$163\,\,167\,\,173\,\,179\,\,181\,\,191\,\,193\,\,197\,\,199\,\,211$").scale(0.0625).shift(DOWN*2)
        n=Tex("$45673$")
        nn=Tex("$45673+1$").shift(DOWN*1)
        self.play(Write(primes))
        self.play(Write(primes2))
        self.play(Write(primes3))
        self.play(Write(primes4))
        self.play(Write(primes5))
        self.wait(7)
        self.play(FadeOut(primes,primes2,primes3,primes4,primes5))
        self.play(Write(n))
        self.wait(19)
        self.play(Write(nn))
        self.wait(15)

class text(Scene):
    def construct(self):
        p=Tex("Divisors of $p=\{1,p\}$").shift(UP*1)
        s=Tex("Sum of divisors $= 1+p$")
        c=Tex("For composite numbers $c$ its greater than $1+c$",color=GREEN).shift(DOWN*1)
        self.wait(7)
        self.play(Write(p))
        self.play(Write(s))
        self.wait(3)
        self.play(Write(c))
        self.wait(7)
        
class div(Scene):
    def construct(self):
        n1=Tex("Sum of divisors of c")
        n2=Tex("$\int c$",color=YELLOW)
        n3=Tex("$\int 15=1+3+5+15=24$")
        self.play(Write(n1))
        self.wait(3)
        self.play(Transform(n1,n2))
        self.wait(8)
        self.play(FadeOut(n1))
        self.play(Write(n3))
        self.wait(10)

class prop(Scene):
    def construct(self):
        p1=Tex("$\int ab$",color=YELLOW).shift(UP*1)
        p2=Tex("$=1+a+b+ab$")
        p3=Tex("$=(1+a)(1+b)$")
        p31=Tex("$=\int a \int b$")
        p4=Tex("$\int \prod\limits_{i=1}^na_i=\prod\limits_{i=1}^n\int a_i=\prod\limits_{i=1}^n(1+a_i)$",color=GREEN).shift(DOWN*1)
        p5=Tex("$\int a^2$",color=YELLOW).shift(UP*1)
        p6=Tex("$=1+a+a^2$")
        p7=Tex("$\dfrac{a^3-1}{a-1}$")
        p8=Tex("$\int a^n=\dfrac{a^{n+1}-1}{a-1}$",color=GREEN).shift(DOWN*1.5)
        p9=Tex("$\int\prod\limits_{i=1}^n a_{i}^{b_i}=\prod\limits_{i=1}^n \int a_{i}^{b_i}$",color=GREEN)
        self.play(Write(p1))
        self.wait(1)
        self.play(Write(p2))
        self.wait(2)
        self.play(Transform(p2,p3))
        self.wait(1)
        self.play(Transform(p2,p31))
        self.wait(3)
        self.play(Write(p4))
        self.wait(3)        
        self.play(FadeOut(p1,p2,p4))
        self.play(Write(p5))
        self.wait(2)
        self.play(Write(p6))
        self.wait(3)
        self.play(Transform(p6,p7))
        self.wait(5)
        self.play(Write(p8))
        self.wait(4)        
        self.play(FadeOut(p5,p6,p8))
        self.play(Write(p9))
        self.wait(10)

class form(Scene):
    def construct(self):
        f=Tex("$\int n=\int (n-1)+\int (n-2)-\int (n-5)-\int (n-7)+\int (n-12)+\int (n-15)-\int (n-22)-\int (n-26)+\ldots$").scale(0.5)
        self.play(Write(f))
        self.wait(33)

class imag(Scene):
    def construct(self):
        t1=Tex("$\int 1=\int 0=1$").shift(UP*3).scale(0.5)
        t2=Tex("$\int 2=\int 1+\int 0=1+2=3$").shift(UP*2.5).scale(0.5)
        t3=Tex("$\int 3=\int 2+\int 1=3+1=4$").shift(UP*2).scale(0.5)
        t4=Tex("$\int 4=\int 3+\int 2 =4+3=7$").shift(UP*1.5).scale(0.5)
        t5=Tex("$\int 5=\int 4+\int 3-\int 0=7+4-5=6$").shift(UP*1).scale(0.5)
        t6=Tex("$\int 6=\int 5+\int 4-\int 1=6+7-1=12$").shift(UP*0.5).scale(0.5)
        t7=Tex("$\int 7=\int 6+\int 5-\int 2-\int 0=12+6-3-7=8$").scale(0.5)
        t8=Tex("$\int 8=\int 7+\int 6-\int 3 -\int 1=8+12-4-1=15$").shift(DOWN*0.5).scale(0.5)
        t9=Tex("$\int 9=\int 8+\int 7-\int 4-\int 2=15+8-7-3=13$").shift(DOWN*1).scale(0.5)
        t10=Tex("$\int 10=\int 9+\int 8-\int 5-\int 3=13+15-6-4=18$").shift(DOWN*1.5).scale(0.5)
        self.play(Write(t1))
        self.play(Write(t2))
        self.play(Write(t3))
        self.play(Write(t4))
        self.play(Write(t5))
        self.play(Write(t6))
        self.play(Write(t7))
        self.play(Write(t8))
        self.play(Write(t9))
        self.play(Write(t10))
        self.wait(15)

class prime(Scene):
    def construct(self):
        t1=Tex("$13$").shift(UP*1)
        t2=Tex("$\int 13=\int 12+\int 11-\int 8-\int 6+\int 1$",color=RED)
        t3=Tex("$28+12-15-12+1=14$",color=RED).shift(DOWN*1)
        t4=Tex("=13+1",color=GREEN).shift(DOWN*2)
        self.play(Write(t1))
        self.play(Write(t2))
        self.play(Write(t3))
        self.play(Write(t4))

class form1(Scene):
    def construct(self):
        f=Tex("$\int n=\int (n-1)+\int (n-2)-\int (n-5)-\int (n-7)+\int (n-12)+\int (n-15)-\int (n-22)-\int (n-26)+\ldots$").scale(0.5)
        f2=Tex("$1,2,5,7,12,15,22,26,\ldots$",color=RED).shift(DOWN*1)
        self.play(Write(f))
        self.play(Write(f2))
        self.wait()

class part(Scene):
    def construct(self):
        f=Tex("$(1-x)(1-x^2)(1-x^3)(1-x^4)\ldots$").scale(0.7).shift(UP*1)
        e=Tex("$=1-x-x^2+x^5+x^7-x^{12}-x^{15}+x^{22}+x^{26}-\ldots$",color=YELLOW).scale(0.7)
        s=Tex("$s=(1-x)(1-x^2)(1-x^3)(1-x^4)\ldots$").scale(0.7).shift(UP*1)
        s1=Tex("$\ln s=\ln (1-x)+\ln (1-x^2)+\ln (1-x^3)+\ln (1-x^4)\ldots$").scale(0.7).shift(UP*1)
        s2=Tex(r"$\dfrac{ds}{s}=\left(\dfrac{-1}{1-x}+\dfrac{-2x}{1-x^2}+\dfrac{-3x^2}{1-x^3}+\ldots \right)dx$").scale(0.7)
        s3=Tex("$\dfrac{-xds}{sdx}=\dfrac{x}{1-x}+\dfrac{2x^2}{1-x^2}+\dfrac{3x^3}{1-x^3}+\ldots$").scale(0.7).shift(DOWN*1)
        s4=Tex("$\dfrac{-xds}{sdx}=\dfrac{x}{1-x}+\dfrac{2x^2}{1-x^2}+\dfrac{3x^3}{1-x^3}+\ldots$").scale(0.4).shift(UP*3)        
        t1=Tex("$s=1-x-x^2+x^5+x^7-x^{12}-x^{15}+x^{22}+x^{26}-\ldots$",color=YELLOW).scale(0.7).shift(UP*1)
        t2=Tex("$\dfrac{ds}{dx}=-1-2x+5x^4+7x^6-12x^{11}-15x^{14}+22x^{21}+26x^{25}-\ldots$",color=YELLOW).scale(0.7)
        t3=Tex("$\dfrac{-xds}{sdx}=\dfrac{x+2x^2-5x^5-7x^7+12x^{12}+15x^{15}-22x^{22}-26x^{26}+\ldots}{1-x-x^2+x^5+x^7-x^{12}-x^{15}+x^{22}+x^{26}-\ldots}$",color=YELLOW).scale(0.7).shift(DOWN*1)
        c=Tex("$\dfrac{-xds}{sdx}=\dfrac{x}{1-x}+\dfrac{2x^2}{1-x^2}+\dfrac{3x^3}{1-x^3}+\ldots$").scale(0.7).shift(UP*1)
        t31=Tex("$t=\dfrac{x+2x^2-5x^5-7x^7+12x^{12}+15x^{15}-22x^{22}-26x^{26}+\ldots}{1-x-x^2+x^5+x^7-x^{12}-x^{15}+x^{22}+x^{26}-\ldots}$").scale(0.7).shift(DOWN*1)
        c1=Tex("$t=\dfrac{x}{1-x}+\dfrac{2x^2}{1-x^2}+\dfrac{3x^3}{1-x^3}+\ldots$").scale(0.7).shift(UP*1)        
        rec=Rectangle(height=1,width=8,color=YELLOW).shift(DOWN*1)
        self.wait(5)
        self.play(Write(f))
        self.wait(2)
        self.play(Write(e))
        self.wait(28)
        self.play(FadeOut(e))
        self.play(Transform(f,s))
        self.play(f.animate.shift(UP*1))
        self.wait(2)
        self.play(Write(s1))
        self.wait(2)
        self.play(Write(s2))
        self.wait(4)
        self.play(Write(s3))
        self.wait(3)
        self.play(Write(rec))
        self.wait(2)
        self.play(FadeOut(rec))
        self.play(Transform(s3,s4))
        self.wait(2)
        self.play(FadeOut(f,s1,s2))
        self.play(Write(t1))
        self.wait(2)
        self.play(Write(t2))
        self.wait(4)
        self.play(Write(t3))
        self.wait(3)
        self.play(FadeOut(t1,t2))
        self.play(Transform(s3,c))
        self.wait(2)
        self.play(Transform(t3,t31),Transform(s3,c1))
        self.wait(15)

class infsum(Scene):
    def construct(self):
        form=Tex("$a+a^2+a^3+a^4\ldots $").scale(0.7).shift(UP*1)
        form1=Tex("$=\dfrac{a}{1-a}$").scale(0.7)
        c1=Tex("$t=\dfrac{x}{1-x}+\dfrac{2x^2}{1-x^2}+\dfrac{3x^3}{1-x^3}+\ldots$").scale(0.7).shift(UP*3)
        rec1=Rectangle(height=1,width=1,color=YELLOW).shift(UP*3+LEFT*1.5)
        e1=Tex("$x+x^2+x^3+x^4+x^5+x^6+\ldots$").scale(0.7).shift(UP*2)
        e2=Tex("$+2x^2\,\,\,\,\,\,\,\,\,\,+2x^4\,\,\,\,\,\,\,\,\,\,+2x^6+\ldots$").scale(0.7).shift(UP*1)
        e3=Tex("$+3x^3\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,+3x^6+\ldots$").scale(0.7).shift(RIGHT*0.3)
        e4=Tex("$+4x^4+\ldots$").scale(0.7).shift(DOWN*1)
        e5=Tex("$+5x^5+\ldots$").scale(0.7).shift(DOWN*2+RIGHT*1)
        e6=Tex("$+6x^6+\ldots$").scale(0.7).shift(DOWN*3+RIGHT*1.5)
        rec2=Rectangle(height=6,width=1,color=YELLOW).shift(DOWN*0.5+RIGHT*1.3)
        rec3=Rectangle(height=5,width=1,color=YELLOW).shift(RIGHT*0.6)
        rec4=Rectangle(height=4,width=1,color=YELLOW).shift(UP*0.5+LEFT*0.4)
        rec5=Rectangle(height=3,width=1,color=YELLOW).shift(UP*1+LEFT*1.1)
        rec6=Rectangle(height=2,width=1,color=YELLOW).shift(UP*1.5+LEFT*1.8)
        rec7=Rectangle(height=1,width=1,color=YELLOW).shift(UP*2+LEFT*2.5)
        self.play(Write(form))
        self.wait(3)
        self.play(Write(form1))
        self.wait(1)
        self.play(FadeOut(form,form1))
        self.play(Write(c1))
        self.wait(2)
        self.play(Write(rec1))
        self.wait(1)
        self.play(Transform(rec1,e1))
        self.play(Write(e2))
        self.play(Write(e3))
        self.play(Write(e4))
        self.play(Write(e5))
        self.play(Write(e6))
        self.wait(5)
        self.play(Write(rec2))
        self.wait(8)
        self.play(Transform(rec2,rec3))
        self.play(Transform(rec2,rec4))
        self.play(Transform(rec2,rec5))
        self.play(Transform(rec2,rec6))
        self.play(Transform(rec2,rec7))
        self.wait(15)

class summing(Scene):
    def construct(self):
        t1s=Tex("$t=\int 1 x+\int 2 x^2+\int 3 x^3+\int 4 x^4+\ldots$",color=GREEN).scale(0.7)
        ct1s=Tex("$t=\int 1 x+\int 2 x^2+\int 3 x^3+\int 4 x^4+\ldots$",color=GREEN).scale(0.4).shift(UP*3)
        t31=Tex("$t=\dfrac{x+2x^2-5x^5-7x^7+12x^{12}+15x^{15}-22x^{22}-26x^{26}+\ldots}{1-x-x^2+x^5+x^7-x^{12}-x^{15}+x^{22}+x^{26}-\ldots}$").scale(0.7)
        nt31=Tex("$t(1-x-x^2+x^5+x^7-x^{12}-x^{15}+x^{22}+x^{26}-\ldots)=x+2x^2-5x^5-7x^7+12x^{12}+15x^{15}-22x^{22}-26x^{26}+\ldots$").scale(0.7)       
        cnt31=Tex("$t(1-x-x^2+x^5+x^7-x^{12}-x^{15}+x^{22}+x^{26}-\ldots)-(x+2x^2-5x^5-7x^7+12x^{12}+15x^{15}-22x^{22}-26x^{26}+\ldots)=0$").scale(0.7)       
        rec=Rectangle(height=1,width=4,color=YELLOW).shift(UP*3)
        self.play(Write(t1s))
        self.wait(5)
        self.play(Transform(t1s,ct1s))
        self.play(Write(t31))
        self.wait(1)
        self.play(Transform(t31,nt31))
        self.play(Transform(t31,cnt31))
        self.wait(2)
        self.play(Write(rec))
        self.wait(10)

class final(Scene):
    def construct(self):
        sub1=Tex("$0=\int 1x+\int 2x^2+\int 3 x^3+\int 4x^4+\int 5x^5+\int 6x^6+\ldots$").scale(0.7).shift(UP*2)
        sub2=Tex("$-x-\int 1 x^2-\int 2x^3-\int 3 x^4-\int 4 x^5-\int 5x^6-\ldots$").scale(0.7).shift(UP*1+RIGHT*0.5)
        sub3=Tex("$-2x^2-\int 1 x^3-\int 2x^4-\int 3 x^5-\int 4 x^6-\ldots$").scale(0.7).shift(RIGHT*1)
        sub4=Tex("$+5 x^5+\int 1 x^6+\ldots$").scale(0.7).shift(DOWN*1+RIGHT*2.7)
        rec=Rectangle(height=4,width=1.5,color=YELLOW).shift(UP*0.5+RIGHT*2.9)
        nt=Tex("$\int 6-\int 5-\int4+\int 1=0$").scale(0.7)
        nt1=Tex("$\int 6=\int 5+\int 4-\int 1$").scale(0.7)
        gen=Tex("$\int n=\int (n-1)+\int (n-2)-\int (n-5)-\int (n-7)+\int (n-12)+\int (n-15)-\int (n-22)-\int (n-26)+\ldots $",color=GREEN).scale(0.7)
        self.play(Write(sub1))
        self.play(Write(sub2))
        self.play(Write(sub3))
        self.play(Write(sub4))
        self.wait(5)
        self.play(Write(rec))
        self.wait(4)
        self.play(FadeOut(sub1,sub2,sub3,sub4),Transform(rec,nt))
        self.wait()
        self.play(Transform(rec,nt1))
        self.wait(10)
        self.play(Transform(rec,gen))
        self.wait(25)
        self.play(FadeOut(rec))

class m(Scene):
    def construct(self):
        e=Tex("$e^{i\pi}$").scale(1.5)
        self.play(Write(e),run_time=5)
